import React from "react";
import MuiAccordion from "@material-ui/core/Accordion";
import MuiAccordionSummary from "@material-ui/core/AccordionSummary";
import MuiAccordionDetails from "@material-ui/core/AccordionDetails";
import Typography from "@material-ui/core/Typography";
// import ArrowDropDownCircleOutlinedIcon from "@material-ui/icons/ExpandMore";
import ArrowDropDownCircleOutlinedIcon from "@material-ui/icons/ArrowDropDownCircleOutlined";
import styled from "styled-components";
import { Grid, makeStyles, Container, List, ListItem, withStyles } from "@material-ui/core";
import SectionTitle from "@components/SectionTitle";

const Accordion = withStyles({
  root: {
    border: "1px solid rgba(0, 0, 0, .125)",
    boxShadow: "none",
    "&:not(:last-child)": {
      borderBottom: 0,
    },
    "&:before": {
      display: "none",
    },
    "&$expanded": {
      margin: "auto",
    },
  },
  expanded: {},
})(MuiAccordion);

const AccordionSummary = withStyles({
  root: {
    backgroundColor: "rgba(0, 0, 0, .03)",
    borderBottom: "1px solid rgba(0, 0, 0, .125)",
    marginBottom: -1,
    minHeight: 56,
    width: "100%",
    "&$expanded": {
      minHeight: 56,
    },
  },
  content: {
    "&$expanded": {
      margin: "12px 0",
    },
  },
  expanded: {},
})(MuiAccordionSummary);

const AccordionDetails = withStyles((theme) => ({
  root: {
    padding: theme.spacing(2),
  },
}))(MuiAccordionDetails);
const useStyles = makeStyles((theme) => ({
  AccordianMain: {
    marginTop: "0px",
    "& .MuiPaper-elevation1": {
      width: "100%",
    },
    paddingBottom: "40px",
    "@media (max-width: 767px)": {
      paddingTop: "25px",
      paddingBottom: "25px",
    },
  },
  list: {
    fontSize: "14px",
    lineHeight: "32px",
    color: "#000",
    fontWeight: "400",
    fontFamily: "Open Sans",
    listStyle: "none",
    paddingLeft: "10px",
    "& li": {
      padding: "0",
    },
    [theme.breakpoints.down("md")]: {
      paddingLeft: "0",
      paddingRight: "0",
    },
  },
  hyperLink: {
    textDecoration: "none",
    color: "#f06425",
  },
}));

function ServiceFAQ() {
  const classes = useStyles();
  const [expanded, setExpanded] = React.useState("panel1");

  const handleChange = (panel) => (event, newExpanded) => {
    setExpanded(newExpanded ? panel : false);
  };

  return (
    <div>
      <Container maxWidth="lg" className={classes.AccordianMain}>
        <TitleDiv>
          <SectionTitle title1="Frequently Asked" title2="Questions" />
        </TitleDiv>
        <Grid container>
          <Accordion square expanded={expanded === "panel1"} onChange={handleChange("panel1")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel1d-content"
              id="panel1d-header"
            >
              <Typography variant="h6">Is the report generated by Japan?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                We always send the original auction sheet. Nothing is added or modified by the company.
              </Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion square expanded={expanded === "panel2"} onChange={handleChange("panel2")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel2d-content"
              id="panel2d-header"
            >
              <Typography variant="h6">What If the auction sheet is not received?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                If you did not receive your auction sheet you can contact us via email or call on our hotline number.
                After verifying all the essential prerequisites, we shall get back to you via email.
              </Typography>
            </AccordionDetails>
          </Accordion>
          <Accordion square expanded={expanded === "panel3"} onChange={handleChange("panel3")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel3d-content"
              id="panel3d-header"
            >
              <Typography variant="h6">How to make the payment for the auction sheet?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>You can make payment through Nagad (+8801700702650).</Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel4"} onChange={handleChange("panel4")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel4d-content"
              id="panel4d-header"
            >
              <Typography variant="h6">Which information is provided in the Auction sheet?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                All the information about your vehicle mileage, grade, accidental, repair, etc are mentioned in the
                report.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel5"} onChange={handleChange("panel5")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel5d-content"
              id="panel5d-header"
            >
              <Typography variant="h6">How will I receive the Auction sheet?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                After depositing the payment, you will receive your auction sheet within a few minutes in your email.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel6"} onChange={handleChange("panel6")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel6d-content"
              id="panel6d-header"
            >
              <Typography variant="h6">What’s the option for unavailability of Chassis number?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                If the auction sheet against your chassis is not available you can contact us through email for manual
                check-in of our report.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel7"} onChange={handleChange("panel7")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel7d-content"
              id="panel7d-header"
            >
              <Typography variant="h6">How to verify Auction sheet from Bangladesh?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Now you can{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/service"}>
                  verify Auction sheet
                </a>{" "}
                of imported Japanese cars through Bhalogari’s website. You have to only enter your car’s Chassis number.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel8"} onChange={handleChange("panel8")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel8d-content"
              id="panel8d-header"
            >
              <Typography variant="h6">Why choose Bhalogari to verify the Auction sheet?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>To get actual details about your car.</Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel9"} onChange={handleChange("panel9")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel9d-content"
              id="panel9d-header"
            >
              <Typography variant="h6">Are your regular services possible at the doorstep?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Yes, regular Service of your car can be done right at your doorstep which are general service. Our team
                of certified mobile mechanics will carry all the tools to do the service at your home or office.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel10"} onChange={handleChange("panel10")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel10d-content"
              id="panel10d-header"
            >
              <Typography variant="h6">What doorstep services do you provide?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                We provide{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/service"}>
                  service combo packages
                </a>
                . You can{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/contact-us"}>
                  contact us
                </a>{" "}
                or call our Hotline number to get more details.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel11"} onChange={handleChange("panel11")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel11d-content"
              id="panel11d-header"
            >
              <Typography variant="h6">
                How much time does it require for Bhalogari take to proceed a service request and what are the
                prerequisites of getting a service from Bhalogari?
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                You will need to request for our doorstep service minimum 24 hours prior to your preferred time/day. The
                number of service hour depends on{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/service"}>
                  what type of servicing
                </a>{" "}
                is required.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel12"} onChange={handleChange("panel12")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel12d-content"
              id="panel12d-header"
            >
              <Typography variant="h6">Is car inspection important?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Inspection is important to identify the condition of your car. For the right service to be recommended
                it is essential to have the right diagnosis.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel13"} onChange={handleChange("panel13")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel13d-content"
              id="panel13d-header"
            >
              <Typography variant="h6">What is the process of doorstep servicing?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                <List component="nav" aria-label="contacts">
                  <ListItem>
                    Process of{" "}
                    <a className={classes.hyperLink} href={"https://www.bhalogari.com/service"}>
                      availing door-step services
                    </a>
                    :
                  </ListItem>
                  <ListItem>1. Click on your desired service</ListItem>
                  <ListItem>2. Fill up the form and Submit</ListItem>
                  <ListItem>3. User will receive a confirmation email</ListItem>
                  <ListItem>4. Service team will contact afterwards and do the needful from there.</ListItem>
                </List>
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel14"} onChange={handleChange("panel14")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel14d-content"
              id="panel14d-header"
            >
              <Typography variant="h6">Where will the inspection of my car be done?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Regular Car Inspection can be done at your doorstep and the{" "}
                <a
                  className={classes.hyperLink}
                  href={
                    "https://www.google.com/maps/place/Bhalogari.com+Service+Centre/@23.7661931,90.4055592,17z/data=!4m6!3m5!1s0x3755b934c990a577:0xf75aeafd7e8a0ca3!4b1!8m2!3d23.7661882!4d90.4077479"
                  }
                >
                  Bhalogari service center
                </a>{" "}
                as well.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel15"} onChange={handleChange("panel15")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel15d-content"
              id="panel15d-header"
            >
              <Typography variant="h6">What services you provide?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Oil change, car wash and polishing, AC diagnosis, Checkup and maintenance, Engine repair and servicing,
                brake servicing, basic servicing, wheel and brake servicing.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel16"} onChange={handleChange("panel16")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel16d-content"
              id="panel16d-header"
            >
              <Typography variant="h6">Why Choose Bhalogari for getting your car inspected?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Simply, because our mission is to provide you with a premium and hassle free{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/service"}>
                  services
                </a>
                . Our platform provides efficient and trust worthy suggestions while using best in class machineries and
                equipment. We are aligned with the government approved regularities whilst ensuring maximum quality and
                safety standards.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel17"} onChange={handleChange("panel17")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel17d-content"
              id="panel17d-header"
            >
              <Typography variant="h6">
                Does Bhalogari inspect a car before approving it for selling or buying?
              </Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                Bhalogari experts inspect every car uploaded on the site to ensure a hassle-free{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/used-car"}>
                  buying
                </a>{" "}
                and{" "}
                <a className={classes.hyperLink} href={"https://www.bhalogari.com/sell-now"}>
                  selling
                </a>{" "}
                experience.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel18"} onChange={handleChange("panel18")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel18d-content"
              id="panel18d-header"
            >
              <Typography variant="h6">What does your inspection cover?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                We will conduct thorough 5 point check of the car at our designated premises. We can add &lsquo;special
                questions&rsquo; so we cover problematic areas or weak spots that may be peculiar to your type car.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel19"} onChange={handleChange("panel19")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel19d-content"
              id="panel19d-header"
            >
              <Typography variant="h6">Do you offer an assessment of the car&apos;s value?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>
                As an add-on to any report, we offer an Opinion of Value, a professional valuation of the vehicle added
                to the report summary which serves as a guide as to what we feel the vehicle is worth in today&apos;s
                market.
              </Typography>
            </AccordionDetails>
          </Accordion>

          <Accordion square expanded={expanded === "panel20"} onChange={handleChange("panel20")}>
            <AccordionSummary
              expandIcon={<ArrowDropDownCircleOutlinedIcon />}
              aria-controls="panel20d-content"
              id="panel20d-header"
            >
              <Typography variant="h6">How much cost is involved for getting a car inspected?</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography>Please contact @ our hotline number for further queries.</Typography>
            </AccordionDetails>
          </Accordion>
        </Grid>
      </Container>
    </div>
  );
}

const TitleDiv = styled.div`
  display: flex;
  // justify-content: center
`;

export default ServiceFAQ;
